[package]
name = "a1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
a1_enable = ["libos/a1_enable"]
a1_disable = ["libos/a1_disable"]

[dependencies]
libos = { path = "../../libos" }
