[package]
name = "a1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
mmu_enable = ["libos/mmu_enable"]
mmu_disable = ["libos/mmu_disable"]

[dependencies]
libos = { path = "../../libos" }
