[package]
name = "a2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
a2_sv39 = ["libos/sv39"]
a2_sv48 = ["libos/sv48"]

[dependencies]
libos = { path = "../../libos" }
